spring.application.name=blood-bank-backend

server.port=8080

# Active profile
spring.profiles.active=local

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# JWT
app.jwt.expiration.ms=900000

# Logging
logging.level.root=INFO
logging.level.com.bloodbank=INFO
logging.level.org.springframework.security=INFO